 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  coco_caption: # name of the dataset builder
    # dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    # build_info:
    #   # Be careful not to append minus sign (-) before split to avoid itemizing
    #   annotations:
    #     train:
    #       url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_train.json
    #       md5: aa31ac474cf6250ebb81d18348a07ed8
    #       storage: /path/to/coco_caption/annotations/coco_karpathy_train.json
    #   images:
    #     storage: /path/to/coco/images/

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_train.json
          md5: aa31ac474cf6250ebb81d18348a07ed8
          storage: /ibex/project/c2090/minigptv2_dataset/coco_captions/coco_karpathy_train.json
        # val:
        #   url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_val.json
        #   md5: b273847456ef5580e33713b1f7de52a0
        #   storage:  /ibex/project/c2133/minigpt4_v2_dataset/coco_caption/annotations/coco_karpathy_val.json
        # test:
        #   url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_test.json
        #   md5: 3ff34b0ef2db02d01c37399f6a2a6cd1
        #   storage: /ibex/project/c2133/minigpt4_v2_dataset/coco_caption/annotations/coco_karpathy_test.json
      images:
        storage: /ibex/reference/CV/COCO/cocoapi/data/2014/images/jpeg